# Generated by Django 5.0.6 on 2024-06-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='if_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_prize',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
