# Generated by Django 5.0.6 on 2024-06-16 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_if_sale_product_sale_prize'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sale_prize',
            new_name='sale_price',
        ),
    ]
