# Generated by Django 5.0.6 on 2024-06-17 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_sale_prize_product_sale_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='category',
            new_name='categories',
        ),
        migrations.RenameModel(
            old_name='customer',
            new_name='customers',
        ),
        migrations.RenameModel(
            old_name='order',
            new_name='orders',
        ),
        migrations.RenameModel(
            old_name='product',
            new_name='products',
        ),
    ]
